on:
  push

name: Test Find and Transition Issue Keys

jobs:
  test-find-and-transition-issue-keys:
    name: Find and Transition Issue Keys
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Find and Transition Issue Key
      uses: ./
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      with:
        issuetypes: Story,Bug
        transitions: In Progress,In Progress